version: '3'
services:
  db:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports: 
      - "3306:3306"
    volumes:
      - ./config/mysql-confd:/etc/mysql/conf.d

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/miditone-server
    ports:
      - "3000:3000"
    links:
      - db
