version: 2.1

executors:
  ubuntu:
    docker:
      # circleci/ruby 2.6.4
      - image: circleci/ruby@sha256:770e381defc5e4a0ba5df52265a96494b9f5d94309234cb3f7bc6b00e1d18f9a

commands:
  restore_gem:
    steps:
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}

  save_gem:
    steps:
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

jobs:
  setup:
    executor: ubuntu
    steps:
      - run: source env.sh
      - run: build
      - run: rake db:create ridgepole:apply
      - save_gem

  rubocop:
    executor: ubuntu
    steps:
      - checkout
      - restore_gem
      - run: rubocop
      - save_gem

  rspec:
    executor: ubuntu
    steps:
      - checkout
      - restore_gem
      - run: rspec
      - save_gem

workflows:
  version: 2.1
  pull-request:
    jobs:
      - setup
      - rubocop:
          requires:
            - setup
      - rspec:
          requires:
            - setup
