version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run: source env.sh
      - run: build
      - run: rake db:create ridgepole:apply

  rubocop:
    steps:
      - run: rubocop

  rspec:
    steps:
      - run: rspec
      
workflows:
  pull-request:
    jobs:
      - build
      - rubocop
          requires:
            - build
      - rspec
          requires:
            - rubocop
