version: 2.1

executors:
  ubuntu:
    machine:
      image: circleci/classic:edge
    working_directory: ~/miditone-server

commands:
  restore_gem:
    steps:
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}

  save_gem:
    steps:
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

jobs:
  setup:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: source env.sh
          command: source env.sh
      - run:
          name: build
          command: build
      - run:
          name: database create & apply
          command: rake db:create ridgepole:apply
      - save_gem

  rubocop:
    executor: ubuntu
    steps:
      - checkout
      - restore_gem
      - run:
          name: rubocop
          command: rubocop
      - save_gem

  rspec:
    executor: ubuntu
    steps:
      - checkout
      - restore_gem
      - run:
          name: rspec
          command: rspec
      - save_gem

workflows:
  version: 2.1
  pull-request:
    jobs:
      - setup
      - rubocop:
          requires:
            - setup
      - rspec:
          requires:
            - setup
